name: build-test

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - beep
    paths-ignore:
      - '**.md'

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 17
        uses: actions/setup-node@v2
        with:
          node-version: 17.x
          cache: npm
      - run: npm ci
      - run: npm run lint

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 17
        uses: actions/setup-node@v2
        with:
          node-version: 17.x
          cache: npm
      - run: npm ci
      - run: npm run build
